### ISSUE TITLE
can't start server

### ISSUE THREAD

**Issue by marcelo321** [rhazdon/hugo-theme-hello-friend-ng#169]
Getting the following error:

```
Building sites … Built in 19 ms
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0" not found in file cache
```

**Comment by pazyp** [comment]
I have the same issue, thought it was just me. Seems to have been around for the last 2 days was working OK on Saturday/Sunday.

**Comment by rhazdon** [comment]
Hi @marcelo321, I will check this right now.

**Comment by rhazdon** [comment]
Sorry, but I can not reproduce tour error. 

My steps:

``` bash
# Create new hugo project and enter directory
hugo new site testPage && cd testPage

# Clone the theme
git clone https://github.com/rhazdon/hugo-theme-hello-friend-ng.git themes/hello-friend-ng

# Create default config.toml (used from README)
cat <<EOF > config.toml
baseurl      = "localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "A simple and beautiful blog"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hello Friend NG"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "hello friend ng"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
EOF

# Start the dev server
hugo server
```

**Comment by pazyp** [comment]
Weird I copied your steps and have the same problem as @marcelo321, I'll try on macOS later on to see if I get the same.

```
[root@localhost src]# hugo new site testPage && cd testPage
Congratulations! Your new Hugo site is created in /root/src/testPage.

Just a few more steps and you're ready to go:

1. Download a theme into the same-named folder.
   Choose a theme from https://themes.gohugo.io/ or
   create your own with the "hugo new theme <THEMENAME>" command.
2. Perhaps you want to add some content. You can add single files
   with "hugo new <SECTIONNAME>/<FILENAME>.<FORMAT>".
3. Start the built-in live server via "hugo server".

Visit https://gohugo.io/ for quickstart guide and full documentation.
[root@localhost testPage]# ls
archetypes  config.toml  content  data  layouts  static  themes
[root@localhost testPage]# git clone https://github.com/rhazdon/hugo-theme-hello-friend-ng.git themes/hello-friend-ng
Cloning into 'themes/hello-friend-ng'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 1583 (delta 13), reused 5 (delta 2), pack-reused 1557
Receiving objects: 100% (1583/1583), 6.49 MiB | 3.55 MiB/s, done.
Resolving deltas: 100% (860/860), done.
[root@localhost testPage]# cat <<EOF > config.toml
> baseurl      = "localhost"
> title        = "My Blog"
> languageCode = "en-us"
> theme        = "hello-friend-ng"
> paginate     = 10
>
> [params]
>   dateform        = "Jan 2, 2006"
>   dateformShort   = "Jan 2"
>   dateformNum     = "2006-01-02"
>   dateformNumTime = "2006-01-02 15:04 -0700"
>
>   # Subtitle for home
>   homeSubtitle = "A simple and beautiful blog"
>
>   # Set disableReadOtherPosts to true in order to hide the links to other posts.
>   disableReadOtherPosts = false
>
>   # Metadata mostly used in document's head
>   description = "My new homepage or blog"
>   keywords = "homepage, blog"
>   images = [""]
>
>   # Default theme "light" or "dark"
>   defaultTheme = "dark"
>
> [taxonomies]
>     category = "blog"
>     tag      = "tags"
>     series   = "series"
>
> [languages]
>   [languages.en]
>     title = "Hello Friend NG"
>     subtitle = "A simple theme for Hugo"
>     keywords = ""
>     copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
>     readOtherPosts = "Read other posts"
>
>     [languages.en.params.logo]
>       logoText = "hello friend ng"
>       logoHomeLink = "/"
>     # or
>     #
>     # path = "/img/your-example-logo.svg"
>     # alt = "Your example logo alt text"
>
>   # And you can even create generic menu
>   [[menu.main]]
>     identifier = "blog"
>     name       = "Blog"
>     url        = "/posts"
> EOF
[root@localhost testPage]# hugo server
Built in 30 ms
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0" not found in file cache
[root@localhost testPage]#
[root@localhost testPage]# hugo -D
Total in 38 ms
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/localhost/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0" not found in file cache
[root@localhost testPage]#
```

**Comment by rhazdon** [comment]
Which hugo version do you use?

I have `Hugo Static Site Generator v0.72.0/extended darwin/amd64 BuildDate: unknown`.

**Comment by pazyp** [comment]
I believe you have craked it, I didnt have extended version.

Version with issue:
```
[root@localhost src]# hugo version
Hugo Static Site Generator v0.72.0-8A7EF3CF linux/386 BuildDate: 2020-05-31T12:05:45Z
```

I quickly pulled down the extended version and the issue is resolved :)
```
[root@localhost hugo]# hugo version
Hugo Static Site Generator v0.72.0-8A7EF3CF/extended linux/amd64 BuildDate: 2020-05-31T12:14:23Z
```

Starting hugo server now has no error.

```
[root@localhost testPage]# hugo server

                   | EN
-------------------+-----
  Pages            |  9
  Paginator pages  |  0
  Non-page files   |  0
  Static files     | 12
  Processed images |  0
  Aliases          |  3
  Sitemaps         |  1
  Cleaned          |  0

Built in 33 ms
Watching for changes in /root/src/testPage/{archetypes,content,data,layouts,static,themes}
Watching for config changes in /root/src/testPage/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

Thanks for the fast response on this!

**Comment by rhazdon** [comment]
Haha, I see... :) 

Installing hugo with homebrew installs the extended version per default: 
https://github.com/Homebrew/homebrew-core/blob/master/Formula/hugo.rb#L22. 

I will add this information to the README. :)

@marcelo321 I hope this solves your issue as well.

**Comment by huseyinsimsekk** [comment]
I installed Hugo bin files on Windows 10 machine.  
Hugo Version is: 
Hugo Static Site Generator v0.74.2-48565DE6 windows/amd64 BuildDate: 2020-07-17T17:22:50Z
I get this error still. I don't understand how you to solve ?
